{
  "server": {
    "host": "localhost",
    "port": 8080,
  },
  "redis": {
    "host": "localhost",
    "port": 6379,
    "password": "",
    "db": "",
  },
  "mongo":{
    "host": "mongodb+srv",
    "username": "venkateshsetti123",
    "password": "6eAeg1jRj5BueUcF",
    "database": "digital_marketing"
  },
  "coingecko":{
    "url": "https://api.coingecko.com/api/v3"
  }
}